import { ChatCompletionTool } from 'openai/resources';
import {
	activities_to_do_tool_function,
	flight_search_tool_function,
	google_flight_tool_function,
	hotels_availability_tool_function,
	list_hotels_in_city_tool_function,
	point_of_interests_tool_function,
} from './tool_calls';

// const flight_offer_search: ChatCompletionTool = {
// 	type: 'function',
// 	function: {
// 		name: 'flight_offer_search',
// 		description: 'Returns a list of available flight offers based on search criteria',
// 		parameters: {
// 			type: 'object',
// 			properties: {
// 				originLocationCode: {
// 					type: 'string',
// 					description: 'The IATA code for the origin location',
// 				},
// 				destinationLocationCode: {
// 					type: 'string',
// 					description: 'The IATA code for the destination location',
// 				},
// 				departureDate: {
// 					type: 'string',
// 					description: 'The departure date in YYYY-MM-DD format',
// 				},
// 				returnDate: {
// 					type: 'string',
// 					description: 'The return date in YYYY-MM-DD format, optional',
// 					optional: true,
// 				},
// 				adults: {
// 					type: 'number',
// 					description: 'Number of adult passengers',
// 				},
// 				children: {
// 					type: 'number',
// 					description: 'Number of child passengers, optional',
// 					optional: true,
// 				},
// 				infants: {
// 					type: 'number',
// 					description: 'Number of infant passengers, optional',
// 					optional: true,
// 				},
// 				travelClass: {
// 					type: 'string',
// 					enum: ['ECONOMY', 'PREMIUS_ECONOMY', 'BUSINESS', 'FIRST'],
// 					description: 'The class of travel, optional',
// 					optional: true,
// 				},
// 				includedAirlineCodes: {
// 					type: 'string',
// 					description:
// 						'Codes of airlines to include in the search, comma-separated, optional',
// 					optional: true,
// 				},
// 				excludedAirlineCodes: {
// 					type: 'string',
// 					description:
// 						'Codes of airlines to exclude from the search, comma-separated, optional',
// 					optional: true,
// 				},
// 				nonStop: {
// 					type: 'boolean',
// 					description: 'Whether to filter for non-stop flights only, optional',
// 					optional: true,
// 				},
// 				currencyCode: {
// 					type: 'string',
// 					description: 'Currency code for pricing, optional',
// 					optional: true,
// 				},
// 				maxPrice: {
// 					type: 'number',
// 					description: 'Maximum price for tickets, optional',
// 					optional: true,
// 				},
// 				max: {
// 					type: 'number',
// 					description: 'Maximum number of offers to return, optional',
// 					optional: true,
// 				},
// 			},
// 			required: ['originLocationCode', 'destinationLocationCode', 'departureDate', 'adults'],
// 		},
// 	},
// };

const flight_offer_search: ChatCompletionTool = {
	type: 'function',
	function: {
		name: 'flight_offer_search',
		description:
			'Find flights based on given criteria including departure and arrival locations, dates, and various preferences regarding airlines, stops, and class of service. Use type 1 for round trip and type 2 for one-way',
		parameters: {
			type: 'object',
			properties: {
				departure_id: {
					type: 'string',
					description: 'Departure airport code or location kgmid, optional',
					optional: true,
				},
				arrival_id: {
					type: 'string',
					description: 'Arrival airport code or location kgmid, optional',
					optional: true,
				},
				currency: {
					type: 'string',
					description: 'Currency of the returned prices, default to USD',
					optional: true,
				},
				type: {
					type: 'number',
					enum: [1, 2, 3],
					description:
						'Type of the flights: 1 for Round trip, 2 for One way. If the user does not give a return date, use 2.',
					optional: true,
				},
				outbound_date: {
					type: 'string',
					description: 'Outbound date in YYYY-MM-DD format, optional',
					optional: true,
				},
				return_date: {
					type: 'string',
					description:
						'Return date in YYYY-MM-DD format, required if type is set to 1 (Round trip)',
					optional: true,
				},
				travel_class: {
					type: 'number',
					enum: [1, 2, 3, 4],
					description:
						'Travel class: 1 for Economy, 2 for Premium economy, 3 for Business, 4 for First, default to Economy',
					optional: true,
				},
				adults: {
					type: 'number',
					description: 'Number of adults, default to 1',
					optional: true,
				},
				children: {
					type: 'number',
					description: 'Number of children',
					optional: true,
				},
				bags: {
					type: 'number',
					description: 'Number of carry-on bags,',
					optional: true,
				},
			},
			required: [],
		},
	},
};

const list_hotels_in_city: ChatCompletionTool = {
	type: 'function',
	function: {
		name: 'list_hotels_in_city',
		description:
			'Search for hotels in a particular city based on various parameters. Contains the "hotelId" of each hotel.',
		parameters: {
			type: 'object',
			properties: {
				cityCode: {
					type: 'string',
					description:
						'The code of the city where the search is conducted. In IATA format',
				},
				radius: {
					type: 'number',
					description: 'The search radius around the city, optional',
					optional: true,
				},
				radiusUnit: {
					type: 'string',
					enum: ['KM', 'MILE'],
					description: 'The unit of measurement for the radius',
					optional: true,
				},
				chainCodes: {
					type: 'array',
					items: {
						type: 'string',
					},
					description: 'List of hotel chain codes to filter the search, optional',
					optional: true,
				},
				amenities: {
					type: 'array',
					items: {
						type: 'string',
						enum: [
							'SWIMMING_POOL',
							'SPA',
							'FITNESS_CENTER',
							'AIR_CONDITIONING',
							'RESTAURANT',
							'PARKING',
							'PETS_ALLOWED',
							'AIRPORT_SHUTTLE',
							'BUSINESS_CENTER',
							'DISABLED_FACILITIES',
							'WIFI',
							'MEETING_ROOMS',
							'NO_KID_ALLOWED',
							'TENNIS',
							'GOLF',
							'KITCHEN',
							'ANIMAL_WATCHING',
							'BABY-SITTING',
							'BEACH',
							'CASINO',
							'JACUZZI',
							'SAUNA',
							'SOLARIUM',
							'MASSAGE',
							'VALET_PARKING',
							'BAR',
							'LOUNGE',
							'KIDS_WELCOME',
							'NO_PORN_FILMS',
							'MINIBAR',
							'TELEVISION',
							'WI-FI_IN_ROOM',
							'ROOM_SERVICE',
							'GUARDED_PARKG',
							'SERV_SPEC_MENU',
						],
					},
					description:
						'List of amenities to filter the search. If no amenities are specified, keep it empty',
					optional: true,
				},
				ratings: {
					type: 'number',
					enum: [1, 2, 3, 4, 5],
					description: "Filter for the hotel's star rating",
					optional: true,
				},
			},
			required: ['cityCode'],
		},
	},
};

const hotels_availability: ChatCompletionTool = {
	type: 'function',
	function: {
		name: 'hotels_availability',
		description:
			'Search the availability of hotels by hotel ID from the list_hotels_in_city API, based on criteria such as check-in and check-out dates, and other filters to determine which hotels are available.',
		parameters: {
			type: 'object',
			properties: {
				hotelIds: {
					type: 'array',
					items: {
						type: 'string',
					},
					description:
						'Array of hotelIds to check availability for. This comes from list_hotels_in_city',
				},
				adults: {
					type: 'number',
					description: 'Number of adults, optional',
					optional: true,
				},
				checkInDate: {
					type: 'string',
					description: 'Check-in date in YYYY-MM-DD format, optional',
					optional: true,
				},
				checkOutDate: {
					type: 'string',
					description: 'Check-out date in YYYY-MM-DD format, optional',
					optional: true,
				},
				countryOfResidence: {
					type: 'string',
					description: 'Country of residence of the guest, optional',
					optional: true,
				},
				roomQuantity: {
					type: 'number',
					description: 'Number of rooms required, optional',
					optional: true,
				},
				priceRange: {
					type: 'string',
					description: 'Desired price range, optional',
					optional: true,
				},
				currency: {
					type: 'string',
					description: 'Currency code, optional',
					optional: true,
				},
				paymentPolicy: {
					type: 'string',
					enum: ['GUARANTEE', 'DEPOSIT', 'NONE'],
					description: 'Payment policy preference, optional',
					optional: true,
				},
				boardType: {
					type: 'string',
					enum: ['ROOM_ONLY', 'BREAKFAST', 'HALF_BOARD', 'FULL_BOARD', 'ALL_INCLUSIVE'],
					description: 'Type of board included with the room',
				},
			},
			required: ['hotelIds', 'boardType'],
		},
	},
};

const activities_to_do: ChatCompletionTool = {
	type: 'function',
	function: {
		name: 'activities_to_do',
		description:
			'List of interesting things to do in the city, based on the specified radius around the city center',
		parameters: {
			type: 'object',
			properties: {
				cityName: {
					type: 'string',
					description:
						'The name of the city where the points of interest are being searched',
				},
				radius: {
					type: 'number',
					description:
						'The search radius from the city center in kilometers, specifying how far the search should extend',
				},
			},
			required: ['cityName', 'radius'],
		},
	},
};

const points_of_interest: ChatCompletionTool = {
	type: 'function',
	function: {
		name: 'points_of_interest',
		description:
			'Find a list of nearby points of interest, such as restaurants, shops, and other services, based on the selected category.',
		parameters: {
			type: 'object',
			properties: {
				city: {
					type: 'string',
					description: 'The city where the points of interest are being searched',
				},
				limit: {
					type: 'number',
					description: 'The maximum number of results to return',
				},
				category: {
					type: 'string',
					enum: [
						'services',
						'shopping',
						'health_services',
						'office',
						'food_and_drink',
						'food',
						'shipping_store',
						'restaurant',
						'education',
						'landscaping',
						'school',
						'real_estate_agent',
						'outdoors',
						'financial_services',
						'doctors_office',
						'grocery',
						'nightlife',
						'hairdresser',
						'lodging',
						'home',
						'auto_repair',
						'place_of_worship',
						'bar',
						'medical_practice',
						'entertainment',
						'clothing_store',
						'consulting',
						'fast_food',
						'bank',
						'insurance_broker',
						'transportation',
						'dentist',
						'lawyer',
						'fitness_center',
						'advertising_agency',
						'car_dealership',
						'beauty_store',
						'park',
						'bakery',
						'electronics_shop',
						'travel_agency',
						'furniture_store',
						'pharmacy',
						'sports',
						'supermarket',
						'tourist_attraction',
						'salon',
						'convenience_store',
						'gas_station',
						'states_and_municipalities',
						'medical_clinic',
						'cafe',
						'church',
						'clothing',
						'psychotherapist',
						'university_building',
						'government',
						'childcare',
						'coffee',
						'coffee_shop',
						'copyshop',
						'alternative_healthcare',
						'tech_startup',
						'farm',
						'pet_store',
						'wholesale_store',
						'jewelry_store',
						'post_office',
						'hospital',
						'shoe_store',
						'employment_agency',
						'atm',
						'phone_store',
						'university',
						'womens_clothing_store',
						'florist',
						'butcher_shop',
						'spa',
						'physiotherapist',
						'factory',
						'photographer',
						'historic_site',
						'veterinarian',
						'breakfast_restaurant',
						'chiropractor',
						'nongovernmental_organization',
						'sports_shop',
						'department_store',
						'nail_salon',
						'mexican_restaurant',
						'temple',
						'car_rental',
						'hotel',
						'monument',
						'vacation_rental',
						'gift_shop',
						'campground',
						'taxi',
						'hardware_store',
						'laundry',
						'psychological_services',
						'fishing',
						'coworking_space',
						'it',
						'dessert_shop',
						'elementary_school',
						'art',
						'book_store',
						'liquor_store',
						'parking_lot',
						'optician',
						'hospital_unit',
						'massage_shop',
						'nightclub',
						'trade_school',
						'bed_and_breakfast',
						'art_gallery',
						'sports_club',
						'driving_school',
						'garden_store',
						'tobacco_shop',
						'event_planner',
						'paper_goods_store',
						'italian_restaurant',
						'fabric_store',
						'garden',
						'storage',
						'car_wash',
						'assisted_living_facility',
						'shopping_mall',
						'music_venue',
						'theatre',
						'fashion_accessory_shop',
						'warehouse',
						'burger_restaurant',
						'library',
						'thrift_shop',
						'theme_park',
						'home_repair',
						'museum',
						'arts_and_craft_store',
						'funeral_home',
						'laboratory',
						'government_offices',
						'charity',
						'field',
						'kindergarten',
						'playground',
						'toy_store',
						'tutor',
						'turkish_restaurant',
						'american_restaurant',
						'ice_cream',
						'medical_supply_store',
						'event_space',
						'beach',
						'deli',
						'police_station',
						'pizza_restaurant',
						'equipment_rental',
						'photo_store',
						'bus_stop',
						'hostel',
						'cinema',
						'counselling',
						'indian_restaurant',
						'tourist_information',
						'studio',
						'locksmith',
						'pub',
						'health_food_store',
						'language_school',
						'seafood_restaurant',
						'dance_studio',
						'information_technology_company',
						'motorcycle_dealer',
						'social_club',
						'teahouse',
						'diner_restaurant',
						'tailor',
						'townhall',
						'bridal_shop',
						'lake',
						'winery',
						'high_school',
						'stadium',
						'antique_shop',
						'bicycle_shop',
						'chinese_restaurant',
						'golf_course',
						'marina',
						'fire_station',
						'railway_station',
						'medical_laboratory',
						'trailhead',
						'care_services',
						'wine_bar',
						'arcade',
						'bus_station',
						'discount_store',
						'market',
						'swimming_pool',
						'brewery',
						'military_base',
						'beer_bar',
						'video_store',
						'martial_arts_studio',
						'cemetery',
						'conference_center',
						'music_shop',
						'music_school',
						'cocktail_bar',
						'mountain',
						'tours',
						'casino',
						'steakhouse',
						'notary',
						'snack_bar',
						'taco_shop',
						'boutique',
						'plaza',
						'resort',
						'charging_station',
						'barbeque_restaurant',
						'dry_cleaners',
						'community_center',
						'yoga_studio',
						'japanese_restaurant',
						'waste_transfer_station',
						'frame_store',
						'courthouse',
						'juice_bar',
						'design_studio',
						'tattoo_parlour',
						'tanning_salon',
						'soccer_field',
						'buffet_restaurant',
						'recycling_center',
						'recreation_center',
						'motel',
						'viewpoint',
						'biergarten',
						'mediterranean_restaurant',
						'sports_bar',
						'spanish_restaurant',
						'asian_restaurant',
						'greek_restaurant',
						'repair_shop',
						'baby_goods_shop',
						'sushi_restaurant',
						'french_restaurant',
						'animal_shelter',
						'fishmonger',
						'forest',
						'radio_studio',
						'dog_park',
						'dormitory',
						'fishing_store',
						'concert_hall',
						'news_kiosk',
						'food_court',
						'hobby_shop',
						'stable',
						'rehabilitation_center',
						'luggage_store',
						'cobbler',
						'university_laboratory',
						'fish_and_chips_restaurant',
						'mosque',
						'recording_studio',
						'wings_joint',
						'stripclub',
						'bowling_alley',
						'racetrack',
						'public_artwork',
						'airport',
						'party_store',
						'dive_bar',
						'german_restaurant',
						'sewing_shop',
						'internet_cafe',
						'bridge',
						'military_office',
						'donut_shop',
						'nature_reserve',
						'photo_lab',
						'gastropub',
						'salad_bar',
						'rest_area',
						'bagel_shop',
						'thai_restaurant',
						'chocolate_shop',
						'tax_advisor',
						'speakeasy',
						'leather_goods',
						'furniture_maker',
						'tapas_restaurant',
						'karaoke_bar',
						'community_college',
						'cheese_shop',
						'hookah_lounge',
						'billiards',
						'emergency_room',
						'tennis_courts',
						'boat_rental',
						'sandwich_shop',
						'video_game_store',
						'camera_shop',
						'arts_center',
						'check_cashing',
						'political_party_office',
						'shoe_repair',
						'watch_store',
						'bookmaker',
						'carpet_store',
						'prison',
						'psychic',
						'brunch_restaurant',
						'water_park',
						'zoo',
						'middle_eastern_restaurant',
						'bike_rental',
						'vineyard',
						'boat_or_ferry',
						'herbalist',
						'ski_area',
						'cruise',
						'beach_bar',
						'television_studio',
						'vietnamese_restaurant',
						'basketball_court',
						'pawnshop',
						'dialysis_center',
						'ski_shop',
						'portuguese_restaurant',
						'hot_dog_stand',
						'carribean_restaurant',
						'pilates_studio',
						'aquarium',
						'embassy',
						'baseball_field',
						'gay_bar',
						'latin_american_restaurant',
						'hunting_store',
						'distillery',
						'vape_shop',
						'lounge',
						'mattress_store',
						'outlet_store',
						'currency_exchange',
						'cannabis_dispensary',
						'fair_grounds',
						'korean_restaurant',
						'surf_spot',
						'gymnastics',
						'summer_camp',
						'fireworks_store',
						'african_restaurant',
						'bubble_tea',
						'pier',
						'university_book_store',
						'ice_rink',
						'public_transportation_station',
						'light_rail_station',
						'road',
						'surfboard_store',
						'turkish_coffeehouse',
						'english_restaurant',
						'skatepark',
						'frozen_yogurt_shop',
						'rafting_spot',
						'fountain',
						'lighthouse',
						'outdoors_store',
						'climbing',
						'airport_terminal',
						'go_kart_racing',
						'apartment_or_condo',
						'miniature_golf',
						'lighting_store',
						'food_truck',
						'synagogue',
						'brazilian_restaurant',
						'cave',
						'tunnel',
						'noodle_restaurant',
						'track',
						'sports_center',
						'kitchen_store',
						'gun_store',
						'hawaiian_restaurant',
						'waterfall',
						'soccer_stadium',
						'boxing_gym',
						'driving_range',
						'pop_up_shop',
						'disc_golf_course',
						'village',
						'canal',
						'ramen_restaurant',
						'coffee_roaster',
						'buddhist_temple',
						'cuban_restaurant',
						'picnic_shelter',
						'indoor_cycling',
						'airport_gate',
						'skydiving_drop_zone',
						'peruvian_restaurant',
						'cricket_club',
						'service_area',
						'filipino_restaurant',
						'railway_platform',
						'observatory',
						'intersection',
						'college',
						'laser_tag',
						'climbing_gym',
						'indonesian_restaurant',
						'sake_bar',
						'neighbourhood',
						'island',
						'football_stadium',
						'bus_line',
						'planetarium',
						'carpet_cleaner',
						'motorsports_store',
						'optometrist',
						'scuba_diving_shop',
						'labor_union',
						'basketball_stadium',
						'creole_restaurant',
						'windmill',
						'persian_restaurant',
						'baseball_stadium',
						'irish_pub',
						'tiki_bar',
						'train',
						'baggage_claim',
						'duty_free_shop',
						'tennis_stadium',
						'city',
						'airport_ticket_counter',
						'meeting_room',
						'town',
						'outdoor_sculpture',
						'theme_park_attraction',
						'zoo_exhibit',
						'korean_barbeque_restaurant',
						'river',
						'gluten_free_restaurant',
						'mountain_hut',
						'beer_festival',
						'hockey_stadium',
						'sauna',
						'tree',
						'champagne_bar',
						'waffle_shop',
						'corporate_amenity',
						'exhibit',
						'well',
						'boat_launch',
						'dam',
						'cable_car',
						'chairlift',
						'racecourse',
						'hunting_area',
						'ski_trail',
						'rugby_stadium',
						'lgbtq_organization',
						'county',
						'state',
						'waste_disposal',
						'country',
						'graffiti',
						'hotel_bar',
						'moving_target',
						'street',
						'treecare',
						'variety_store',
						'veterans_service',
						'whiskey_bar',
					],
					description: 'The specific category of interest to filter the search results',
				},
			},
			required: ['city', 'limit', 'category'],
		},
	},
};

export const tools: ChatCompletionTool[] = [
	flight_offer_search,
	// list_hotels_in_city,
	// hotels_availability,
	// activities_to_do,
	points_of_interest,
];
export const availableFunctions = {
	flight_offer_search: google_flight_tool_function,
	list_hotels_in_city: list_hotels_in_city_tool_function,
	hotels_availability: hotels_availability_tool_function,
	// activities_to_do: activities_to_do_tool_function,
	points_of_interest: point_of_interests_tool_function,
};
